<a href="https://colab.research.google.com/github/lokeshBI/pythoncodes/blob/master/ANN_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
# To import files from your local system.
from google.colab import files
uploaded = files.upload()
import io
import pandas as pd
churn_data = pd.read_csv(io.BytesIO(uploaded['Churn_Modelling.csv']))

Saving Churn_Modelling.csv to Churn_Modelling.csv


In [8]:
churn_data.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [9]:
churn_data.dtypes

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

## Here we are dealing with classification problem.
## Our target variable is 'Exited' to classify whether they will be in or out of bank.
# Data Preprocessing


In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [0]:
# split the data into inputs and response variables
X= churn_data.iloc[:, 3:13].values # upper bound exculded so 13.
y = churn_data.iloc[:,13].values

In [12]:
print(X, '\n')
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]] 

[1 0 1 ... 1 1 0]


In [15]:
# In our data we have factor data so we need to encode it
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
label_encoder_x1 = LabelEncoder()
label_encoder_x2 = LabelEncoder()
X[:,1] = label_encoder_x1.fit_transform(X[:,1])
X[:,2] = label_encoder_x2.fit_transform(X[:,2])
onehotencoder = OneHotEncoder(categorical_features = [1]) # here we do onehotencoding for country column only because it shows order like 1,2 and 3 when it labelencoded.
X = onehotencoder.fit_transform(X).toarray()

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [16]:
print(X,'\n')
print(y)

[[1.0000000e+00 0.0000000e+00 0.0000000e+00 ... 1.0000000e+00
  1.0000000e+00 1.0134888e+05]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00 ... 0.0000000e+00
  1.0000000e+00 1.1254258e+05]
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 ... 1.0000000e+00
  0.0000000e+00 1.1393157e+05]
 ...
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  1.0000000e+00 4.2085580e+04]
 [0.0000000e+00 1.0000000e+00 0.0000000e+00 ... 1.0000000e+00
  0.0000000e+00 9.2888520e+04]
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 ... 1.0000000e+00
  0.0000000e+00 3.8190780e+04]] 

[1 0 1 ... 1 1 0]


In [0]:
# here we converted all country column into dummy variables so inorder to avoid dummy variable trap we have to take 2 dummy columns out of 3.
X = X[:, 1:]

In [19]:
print(X)

[[0.0000000e+00 0.0000000e+00 6.1900000e+02 ... 1.0000000e+00
  1.0000000e+00 1.0134888e+05]
 [0.0000000e+00 1.0000000e+00 6.0800000e+02 ... 0.0000000e+00
  1.0000000e+00 1.1254258e+05]
 [0.0000000e+00 0.0000000e+00 5.0200000e+02 ... 1.0000000e+00
  0.0000000e+00 1.1393157e+05]
 ...
 [0.0000000e+00 0.0000000e+00 7.0900000e+02 ... 0.0000000e+00
  1.0000000e+00 4.2085580e+04]
 [1.0000000e+00 0.0000000e+00 7.7200000e+02 ... 1.0000000e+00
  0.0000000e+00 9.2888520e+04]
 [0.0000000e+00 0.0000000e+00 7.9200000e+02 ... 1.0000000e+00
  0.0000000e+00 3.8190780e+04]]


In [0]:
# split the data into train and test
from sklearn.model_selection import train_test_split
X_trian, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state =0)

In [0]:
# feature scaling is necessary in deep learning models
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_trian = sc.fit_transform(X_trian)
X_test = sc.transform(X_test)

In [23]:
print(X_trian,'\n')
print(X_test)

[[-0.5698444   1.74309049  0.16958176 ...  0.64259497 -1.03227043
   1.10643166]
 [ 1.75486502 -0.57369368 -2.30455945 ...  0.64259497  0.9687384
  -0.74866447]
 [-0.5698444  -0.57369368 -1.19119591 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [-0.5698444  -0.57369368  0.9015152  ...  0.64259497 -1.03227043
   1.41231994]
 [-0.5698444   1.74309049 -0.62420521 ...  0.64259497  0.9687384
   0.84432121]
 [ 1.75486502 -0.57369368 -0.28401079 ...  0.64259497 -1.03227043
   0.32472465]] 

[[ 1.75486502 -0.57369368 -0.55204276 ...  0.64259497  0.9687384
   1.61085707]
 [-0.5698444  -0.57369368 -1.31490297 ...  0.64259497 -1.03227043
   0.49587037]
 [-0.5698444   1.74309049  0.57162971 ...  0.64259497  0.9687384
  -0.42478674]
 ...
 [-0.5698444   1.74309049 -0.74791227 ...  0.64259497 -1.03227043
   0.71888467]
 [ 1.75486502 -0.57369368 -0.00566991 ...  0.64259497  0.9687384
  -1.54507805]
 [ 1.75486502 -0.57369368 -0.79945688 ...  0.64259497 -1.03227043
   1.61255917]]


In [0]:
# ANN model building & required packages
import keras
from keras.models import Sequential  # to initialize the model
from keras.layers import Dense       # for layers  

In [25]:
# Initializing the ANN
classifier = Sequential()

In [27]:
# Adding the input layer and first hidden layers.

# Will choose activation functions : hidden layer --> rectifier function, output layer --> sigmoid function.
# To add no.of hidden layers as rule of thumb = (input nodes + output node) / 2, (11+ 1)/2 = 6.
# We have to initialize the weights, here we are using 'uniform' function to assign weights uniformly.
classifier.add(Dense(output_dim = 6, init = 'uniform', activation='relu', input_dim = 11 ))



/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [28]:
# Adding second hidden layer, as this is second hidden layer we don't need to specify input nodes.
classifier.add(Dense(output_dim = 6, init = 'uniform', activation='relu'))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [29]:
# Adding the output layer, activation function = 'sigmoid' if you have two classes and if it will be 3 classes then use 'softmax'
classifier.add(Dense(output_dim = 1, init = 'uniform', activation='sigmoid'))


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [30]:
# compiling the ANN, optimizer = 'adam' algorithm, loss function --> binary crossentropy
classifier.compile(optimizer = 'adam', loss= 'binary_crossentropy', metrics= ['accuracy'])



Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [32]:
# Fitting ANN to the training set
classifier.fit(X_trian, y_train, batch_size=10, epochs= 100)




Epoch 1/100





8000/8000 [==============================] - 2s 205us/step - loss: 0.4848 - acc: 0.7984
Epoch 2/100
8000/8000 [==============================] - 1s 128us/step - loss: 0.4074 - acc: 0.8230
Epoch 3/100
8000/8000 [==============================] - 1s 131us/step - loss: 0.3939 - acc: 0.8274
Epoch 4/100
8000/8000 [==============================] - 1s 129us/step - loss: 0.3844 - acc: 0.8301
Epoch 5/100
8000/8000 [==============================] - 1s 126us/step - loss: 0.3781 - acc: 0.8324
Epoch 6/100
8000/8000 [==============================] - 1s 129us/step - loss: 0.3731 - acc: 0.8435
Epoch 7/100
8000/8000 [==============================] - 1s 130us/step - loss: 0.3687 - acc: 0.8479
Epoch 8/100
8000/8000 [==============================] - 1s 128us/step - loss: 0.3654 - acc: 0.8534
Epoch 9/100
8000/8000 [==============================] - 1s 130us/step - loss: 0.3624 - acc: 0.8507
Epoch 10/100
8000/8000 [==============================] - 1s 128us/step - loss: 0.3600 - acc

In [0]:
y_pred = classifier.predict(X_test)

In [34]:
y_pred

array([[0.16167012],
       [0.23018748],
       [0.10274157],
       ...,
       [0.18870103],
       [0.13086444],
       [0.2954541 ]], dtype=float32)

In [35]:
y_pred = (y_pred > 0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [36]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1533,   62],
       [ 205,  200]])